plot()
xlab("X Axis Label")
ylab("Y Axis Label")
main("Empty Plot")
plot(xlim = c(0, 10), ylim = c(0, 20))
xlab("X Axis Label")
ylab("Y Axis Label")
main("Empty Plot with Axis Limits")
dev.off()
